Repository yobta/stores, pull requests merged in 2023-01, with the labels that each got.

#38 fix: machineYobta typings
  src/stores/machineYobta/index.md
  src/stores/machineYobta/index.ts
Labels: require review

#42 fix: imports
  src/adapters/react/index.md
  src/util/mapCodecYobta/index.md
Labels: require review

#43 fix: typo Machine -> Map
  src/stores/mapYobta/index.md
Labels: require review

#44 fix: typoe Machine -> Plain Object
  src/stores/plainObjectYobta/index.md
Labels: require review

#45 fix: typo
  src/plugins/index.md
Labels: require review

#46 fix: plain js enstead ts
  src/plugins/validationPluginYobta/index.md
Labels: require review

#37 fix: overoads typos and typings
  src/stores/storeYobta/index.md
Labels: invalid

#51 Fix docs
  src/stores/storeYobta/index.md
  src/util/pubSubYobta/index.md
  src/util/transitionEffectYobta/index.md
Labels: require review

#52 connectivity store
  CHANGELOG.md
  README.md
  package.json
  src/index.ts
  src/stores/onlineYobta/index.md
  src/stores/onlineYobta/index.test.ts
  src/stores/onlineYobta/index.ts
  src/util/readableYobta/index.md
  src/util/readableYobta/index.test.ts
  src/util/readableYobta/index.ts
Labels: ready for merge
